android-pixel-8:
  type: instrumentation
  app: app-debug/app-debug.apk
  test: app-debug-androidTest/app-debug-androidTest.apk
  device:
    - model: shiba
      version: 34
      locale: 'en'
      orientation: portrait