package com.ivangarzab.carrus.ui.compose.theme
import androidx.compose.ui.graphics.Color

/**
 * Created by Ivan Garza Bermea.
 */
val indigo = Color(0xFF3F00FF)
val mediterraneo = Color(0xFF006781)
val caribe = Color(0xFF00cc99)
val gigas = Color(0xFF483d8b)
val crimson = Color(0xFFe8000d)

val md_theme_light_primary = Color(0xFF006781)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFB9EAFF)
val md_theme_light_onPrimaryContainer = Color(0xFF001F29)
val md_theme_light_secondary = Color(0xFF006C4F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF5DFCC6)
val md_theme_light_onSecondaryContainer = Color(0xFF002116)
val md_theme_light_tertiary = Color(0xFF5E52A7)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE5DEFF)
val md_theme_light_onTertiaryContainer = Color(0xFF190261)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD5)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFDF9)
val md_theme_light_onBackground = Color(0xFF191C1A)
val md_theme_light_surface = Color(0xFFF8FAF6)
val md_theme_light_onSurface = Color(0xFF191C1A)
val md_theme_light_surfaceVariant = Color(0xFFE6F0F2)
val md_theme_light_onSurfaceVariant = Color(0xFF40484C)
val md_theme_light_inverseSurface = Color(0xFF2E3132)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F2)
val md_theme_light_surfaceTint = Color(0xFF006781)
val md_theme_light_inversePrimary = Color(0xFF00cc99)
val md_theme_light_outline = Color(0xFF70787C)
val md_theme_light_outlineVariant = Color(0xFFC0C8CC)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF00cc99)
val md_theme_dark_onPrimary = Color(0xFF003828)
val md_theme_dark_primaryContainer = Color(0xFF00513B)
val md_theme_dark_onPrimaryContainer = Color(0xFF5DFCC6)
val md_theme_dark_secondary = Color(0xFF5FD4FD)
val md_theme_dark_onSecondary = Color(0xFF003544)
val md_theme_dark_secondaryContainer = Color(0xFF004D62)
val md_theme_dark_onSecondaryContainer = Color(0xFFB9EAFF)
val md_theme_dark_tertiary = Color(0xFFC8BFFF)
val md_theme_dark_onTertiary = Color(0xFF2F2176)
val md_theme_dark_tertiaryContainer = Color(0xFF463A8D)
val md_theme_dark_onTertiaryContainer = Color(0xFFE5DEFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690004)
val md_theme_dark_errorContainer = Color(0xFF930009)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD5)
val md_theme_dark_background = Color(0xFF191C1D)
val md_theme_dark_onBackground = Color(0xFFE1E3E4)
val md_theme_dark_surface = Color(0xFF111415)
val md_theme_dark_onSurface = Color(0xFFC5C7C8)
val md_theme_dark_surfaceVariant = Color(0xFF23282A)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C8CC)
val md_theme_dark_inverseSurface = Color(0xFFE1E3E4)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1D)
val md_theme_dark_surfaceTint = Color(0xFF5FD4FD)
val md_theme_dark_inversePrimary = Color(0xFF006781)
val md_theme_dark_outline = Color(0xFF8A9296)
val md_theme_dark_outlineVariant = Color(0xFF40484C)
val md_theme_dark_scrim = Color(0xFF000000)