package com.ivangarzab.carrus.ui.compose.theme
import androidx.compose.ui.graphics.Color

/**
 * Created by Ivan Garza Bermea.
 */
val seed = Color(0xFF3F00FF)
val blue = Color(0xFF006781)
val green = Color(0xFF00cc99)

val md_theme_light_primary = Color(0xFF006781)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE6F0F2)
val md_theme_light_onPrimaryContainer = Color(0xFF002B36)
val md_theme_light_secondary = Color(0xFF00BA8B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF8AE8D0)
val md_theme_light_onSecondaryContainer = Color(0xFF002B36)
val md_theme_light_tertiary = Color(0xFF7A54FF)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE6E6FF)
val md_theme_light_onTertiaryContainer = Color(0xFF1A006B)
val md_theme_light_error = Color(0xFFBB1800)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD3)
val md_theme_light_onErrorContainer = Color(0xFF3F0300)
val md_theme_light_outline = Color(0xFF787680)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFCF8FD)
val md_theme_light_onSurface = Color(0xFF1C1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE5E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF47464F)
val md_theme_light_inverseSurface = Color(0xFF313034)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inversePrimary = Color(0xFF00cc99)
val md_theme_light_surfaceTint = Color(0xFF006781)
val md_theme_light_outlineVariant = Color(0xFFC8C5D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF00cc99)
val md_theme_dark_onPrimary = Color(0xFF002B36)
val md_theme_dark_primaryContainer = Color(0xFF006781)
val md_theme_dark_onPrimaryContainer = Color(0xFFE3DFFF)
val md_theme_dark_secondary = Color(0xFF5499AB)
val md_theme_dark_onSecondary = Color(0xFF003947)
val md_theme_dark_secondaryContainer = Color(0xFF5499AB)
val md_theme_dark_onSecondaryContainer = Color(0xFF93F993)
val md_theme_dark_tertiary = Color(0xFFC1C1FF)
val md_theme_dark_onTertiary = Color(0xFF242478)
val md_theme_dark_tertiaryContainer = Color(0xFF3B3D8F)
val md_theme_dark_onTertiaryContainer = Color(0xFFE1DFFF)
val md_theme_dark_error = Color(0xFFFFB4A6)
val md_theme_dark_onError = Color(0xFF660800)
val md_theme_dark_errorContainer = Color(0xFF8F1000)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD3)
val md_theme_dark_outline = Color(0xFF928F99)
val md_theme_dark_background = Color(0xFF1C1B1F)
val md_theme_dark_onBackground = Color(0xFFE5E1E6)
val md_theme_dark_surface = Color(0xFF141316)
val md_theme_dark_onSurface = Color(0xFFC9C5CA)
val md_theme_dark_surfaceVariant = Color(0xFF47464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC8C5D0)
val md_theme_dark_inverseSurface = Color(0xFFE5E1E6)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1F)
val md_theme_dark_inversePrimary = Color(0xFF006781)
val md_theme_dark_surfaceTint = Color(0xFFC5C0FF)
val md_theme_dark_outlineVariant = Color(0xFF47464F)
val md_theme_dark_scrim = Color(0xFF000000)